insert into public.topic_scripts (
    topic_registry_id,
    post_type,
    title,
    script,
    target_length_tier,
    bucket,
    hook_style,
    framework,
    tone,
    estimated_duration_s,
    lane_key,
    lane_family,
    cluster_id,
    anchor_topic,
    disclaimer,
    source_summary,
    primary_source_url,
    primary_source_title,
    source_urls,
    seed_payload,
    quality_notes,
    use_count,
    created_at,
    updated_at
)
select
    tr.id as topic_registry_id,
    tr.post_type,
    tr.title,
    variant->>'script' as script,
    coalesce((tier.key)::int, 16) as target_length_tier,
    variant->>'bucket' as bucket,
    variant->>'hook_style' as hook_style,
    variant->>'framework' as framework,
    variant->>'tone' as tone,
    nullif(variant->>'estimated_duration_s', '')::int as estimated_duration_s,
    variant->>'lane_key' as lane_key,
    variant->>'lane_family' as lane_family,
    variant->>'cluster_id' as cluster_id,
    variant->>'anchor_topic' as anchor_topic,
    variant->>'disclaimer' as disclaimer,
    variant->>'source_summary' as source_summary,
    variant->>'primary_source_url' as primary_source_url,
    variant->>'source_title' as primary_source_title,
    coalesce(variant->'source_urls', '[]'::jsonb) as source_urls,
    coalesce(tr.seed_payloads -> tier.key, '{}'::jsonb) as seed_payload,
    ''::text as quality_notes,
    0 as use_count,
    coalesce(tr.last_harvested_at, tr.first_seen_at, now()) as created_at,
    now() as updated_at
from public.topic_registry tr
join lateral jsonb_each(coalesce(tr.script_bank, '{}'::jsonb)) tier(key, value) on true
join lateral jsonb_array_elements(tier.value) variant on true
on conflict (topic_registry_id, target_length_tier, script) do nothing;
