"""
Video Generation Polling Worker
Runs on Railway, polls VEO/Sora operations and updates Supabase.
Per Constitution § III: Deterministic Execution
Per Constitution § IX: Observable Implementation
"""

import time
import sys
import os
import json
import socket
import subprocess
import tempfile
from urllib.parse import quote
from datetime import datetime, timedelta, timezone
from typing import List, Dict, Any, Optional, Union
import httpx
import google.auth
from google.auth.transport.requests import Request

# Add parent directory to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.adapters.supabase_client import get_supabase
from app.adapters.sora_client import get_sora_client
from app.adapters.storage_client import get_storage_client
from app.core.logging import configure_logging, get_logger
from app.core.config import get_settings, google_ai_context_fingerprint, resolve_google_application_credentials_path
from app.core.errors import FlowForgeException, ValidationError
from app.features.batches.state_machine import reconcile_batch_video_pipeline_state
from app.features.videos.prompt_audit import record_prompt_audit
from app.features.videos.quota_guard import (
    build_reservation_key,
    consume_quota,
    ensure_immediate_submit_slot,
    maybe_freeze_after_provider_429,
    release_quota,
    reserve_quota,
)
from app.core.video_profiles import (
    get_pollable_video_statuses,
    VEO_EXTENDED_VIDEO_ROUTE,
    VIDEO_STATUS_CAPTION_COMPLETED,
    VIDEO_STATUS_CAPTION_PENDING,
    VIDEO_STATUS_COMPLETED,
    VIDEO_STATUS_FAILED,
    get_processing_video_status,
    get_submitted_video_status,
    TRIM_TAIL_MS,
)

try:  # pragma: no cover - allow worker to run without google-genai on Python 3.9
    from app.adapters.veo_client import get_veo_client  # type: ignore
    _veo_available = True
    _veo_import_error = None
except Exception as import_error:  # noqa: BLE001
    get_veo_client = None  # type: ignore
    _veo_available = False
    _veo_import_error = import_error

try:  # pragma: no cover - allow worker to run without Vertex AI SDK
    from app.adapters.vertex_ai_client import get_vertex_ai_client  # type: ignore
    _vertex_ai_available = True
    _vertex_ai_import_error = None
except Exception as import_error:  # noqa: BLE001
    get_vertex_ai_client = None  # type: ignore
    _vertex_ai_available = False
    _vertex_ai_import_error = import_error

# Configure logging
configure_logging()
logger = get_logger(__name__)

logger.info(
    "video_poller_startup_context",
    **google_ai_context_fingerprint(),
)


def _ensure_google_adc_env() -> None:
    adc_path = resolve_google_application_credentials_path()
    if adc_path and not os.getenv("GOOGLE_APPLICATION_CREDENTIALS"):
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = adc_path

if not _veo_available:
    logger.warning(
        "veo_client_unavailable",
        error=str(_veo_import_error),
        message="VEO polling disabled; continuing with available providers"
    )

POLL_INTERVAL_SECONDS = 10
MAX_RETRIES = 3
RAI_MAX_RETRIES = 3
VIDEO_POLL_LEASE_SECONDS = max(POLL_INTERVAL_SECONDS * 3, 30)
VIDEO_POLL_LEASE_OWNER_KEY = "video_poll_lease_owner"
VIDEO_POLL_LEASE_ACQUIRED_KEY = "video_poll_lease_acquired_at"
VIDEO_POLL_LEASE_EXPIRES_KEY = "video_poll_lease_expires_at"
VEO_EXTENSION_RETRY_BACKOFF_SECONDS = (15, 30, 60, 120)
VEO_EXTENSION_INPUT_NOT_READY_MESSAGE = (
    "Input video must be a video that was generated by VEO that has been processed."
)


def _poller_identity() -> str:
    settings = get_settings()
    configured = (settings.video_poller_identity or "").strip()
    if configured:
        return configured
    return f"{socket.gethostname()}:{os.getpid()}"


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _utc_now_iso(now: Optional[datetime] = None) -> str:
    current = now or _utc_now()
    return current.replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _quota_controls_bypassed() -> bool:
    settings = get_settings()
    return bool(
        settings.veo_disable_local_quota_guard
        or settings.veo_disable_all_quota_controls
    )


def _consume_quota_after_acceptance(
    *,
    reservation_key: Optional[str],
    operation_id: str,
    units: int,
    correlation_id: str,
    post_id: str,
) -> Optional[str]:
    if not reservation_key:
        return None
    try:
        consume_quota(
            reservation_key=reservation_key,
            operation_id=operation_id,
            units=units,
        )
        return None
    except FlowForgeException as exc:
        logger.error(
            "quota_consume_failed_after_provider_acceptance",
            post_id=post_id,
            correlation_id=correlation_id,
            reservation_key=reservation_key,
            operation_id=operation_id,
            code=str(exc.code),
            message=exc.message,
            details=exc.details,
        )
        return exc.message


def _parse_utc_timestamp(value: Any) -> Optional[datetime]:
    if not value or not isinstance(value, str):
        return None

    candidate = value.strip()
    if not candidate:
        return None

    if candidate.endswith("Z"):
        candidate = candidate[:-1] + "+00:00"

    try:
        parsed = datetime.fromisoformat(candidate)
    except ValueError:
        return None

    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)

    return parsed.astimezone(timezone.utc)


def _lease_is_active(metadata: Optional[Dict[str, Any]], *, now: Optional[datetime] = None) -> bool:
    if not metadata:
        return False

    expires_at = _parse_utc_timestamp(metadata.get(VIDEO_POLL_LEASE_EXPIRES_KEY))
    if expires_at is None:
        return False

    current = now or _utc_now()
    return expires_at > current


def _quota_reservation_key(metadata: Optional[Dict[str, Any]]) -> Optional[str]:
    if not metadata:
        return None
    value = metadata.get("quota_reservation_key")
    if not value:
        return None
    return str(value)


def _release_post_quota_reservation(
    post: Dict[str, Any],
    *,
    reason: str,
    final_status: str,
    error_code: Optional[str] = None,
) -> None:
    reservation_key = _quota_reservation_key(post.get("video_metadata") or {})
    if not reservation_key:
        return
    release_quota(
        reservation_key=reservation_key,
        reason=reason,
        final_status=final_status,
        error_code=error_code,
    )


def _claim_video_poll_lease(post: Dict[str, Any], correlation_id: str) -> Optional[Dict[str, Any]]:
    post_id = post["id"]
    poller_identity = _poller_identity()
    metadata = dict(post.get("video_metadata") or {})
    now = _utc_now()

    lease_owner = metadata.get(VIDEO_POLL_LEASE_OWNER_KEY)
    if lease_owner and lease_owner != poller_identity and _lease_is_active(metadata, now=now):
        logger.info(
            "video_poll_lease_held_by_other_worker",
            post_id=post_id,
            correlation_id=correlation_id,
            poller_identity=poller_identity,
            lease_owner=lease_owner,
            lease_expires_at=metadata.get(VIDEO_POLL_LEASE_EXPIRES_KEY),
        )
        return None

    updated_at = post.get("updated_at")
    if not updated_at:
        logger.warning(
            "video_poll_lease_missing_updated_at",
            post_id=post_id,
            correlation_id=correlation_id,
            message="Proceeding without compare-and-set lease guard",
        )
        return post

    lease_acquired_at = _utc_now_iso(now)
    lease_expires_at = _utc_now_iso(now + timedelta(seconds=VIDEO_POLL_LEASE_SECONDS))
    claimed_metadata = {
        **metadata,
        VIDEO_POLL_LEASE_OWNER_KEY: poller_identity,
        VIDEO_POLL_LEASE_ACQUIRED_KEY: lease_acquired_at,
        VIDEO_POLL_LEASE_EXPIRES_KEY: lease_expires_at,
        "last_polled_by": poller_identity,
        "last_polled_at": lease_acquired_at,
    }

    supabase = get_supabase().client
    claim_response = (
        supabase.table("posts")
        .update({"video_metadata": claimed_metadata})
        .eq("id", post_id)
        .eq("updated_at", updated_at)
        .execute()
    )
    claimed_rows = claim_response.data or []

    if not claimed_rows:
        logger.info(
            "video_poll_lease_claim_conflict",
            post_id=post_id,
            correlation_id=correlation_id,
            poller_identity=poller_identity,
            expected_updated_at=updated_at,
        )
        return None

    claimed_post = dict(post)
    claimed_post.update(claimed_rows[0])
    claimed_post["video_metadata"] = claimed_metadata

    logger.debug(
        "video_poll_lease_claimed",
        post_id=post_id,
        correlation_id=correlation_id,
        poller_identity=poller_identity,
        lease_expires_at=lease_expires_at,
    )
    return claimed_post


def _failure_metadata(
    *,
    error: Exception,
    provider: str,
    operation_id: str,
) -> Dict[str, Any]:
    metadata: Dict[str, Any] = {
        "error": str(error),
        "error_type": error.__class__.__name__,
        "provider": provider,
        "operation_id": operation_id,
        "last_polled_by": _poller_identity(),
        "failed_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    if isinstance(error, httpx.HTTPStatusError):
        metadata["provider_status_code"] = error.response.status_code
        metadata["provider_response_body"] = error.response.text[:4000]
    return metadata


def _is_retryable_veo_extension_input_not_ready(error: Exception) -> bool:
    if not isinstance(error, httpx.HTTPStatusError):
        return False
    if error.response.status_code != 400:
        return False

    message = ""
    try:
        payload = error.response.json()
    except ValueError:
        payload = None

    if isinstance(payload, dict):
        provider_error = payload.get("error")
        if isinstance(provider_error, dict):
            message = str(provider_error.get("message") or "")

    if not message:
        message = error.response.text

    return VEO_EXTENSION_INPUT_NOT_READY_MESSAGE in message


def _veo_extension_retry_delay_seconds(retry_count: int) -> int:
    if retry_count <= 0:
        return VEO_EXTENSION_RETRY_BACKOFF_SECONDS[0]
    index = min(retry_count - 1, len(VEO_EXTENSION_RETRY_BACKOFF_SECONDS) - 1)
    return VEO_EXTENSION_RETRY_BACKOFF_SECONDS[index]


def _defer_extension_hop_retry(
    *,
    post_id: str,
    metadata: Dict[str, Any],
    correlation_id: str,
    error: httpx.HTTPStatusError,
) -> None:
    retry_count = int(metadata.get("veo_extension_input_retry_count") or 0) + 1
    delay_seconds = _veo_extension_retry_delay_seconds(retry_count)
    retry_after = _utc_now() + timedelta(seconds=delay_seconds)

    error_message = ""
    try:
        payload = error.response.json()
    except ValueError:
        payload = None

    if isinstance(payload, dict):
        provider_error = payload.get("error")
        if isinstance(provider_error, dict):
            error_message = str(provider_error.get("message") or "")
    if not error_message:
        error_message = error.response.text[:4000]

    metadata.update(
        {
            "chain_status": "waiting_for_extension_input_processing",
            "veo_extension_input_retry_count": retry_count,
            "veo_extension_retry_after": _utc_now_iso(retry_after),
            "veo_extension_last_retryable_error": error_message,
            "provider_status_code": error.response.status_code,
            "provider_response_body": error.response.text[:4000],
            "last_polled_by": _poller_identity(),
            "last_polled_at": _utc_now_iso(),
        }
    )

    supabase = get_supabase().client
    supabase.table("posts").update(
        {
            "video_status": get_processing_video_status(VEO_EXTENDED_VIDEO_ROUTE),
            "video_metadata": metadata,
        }
    ).eq("id", post_id).execute()

    logger.warning(
        "extension_hop_deferred_waiting_for_processed_video",
        post_id=post_id,
        correlation_id=correlation_id,
        retry_count=retry_count,
        retry_after=metadata["veo_extension_retry_after"],
        delay_seconds=delay_seconds,
        provider_status_code=error.response.status_code,
    )


def _parse_aspect_ratio(value: str) -> tuple[int, int]:
    width_str, height_str = value.split(":", 1)
    width = int(width_str)
    height = int(height_str)
    if width <= 0 or height <= 0:
        raise ValueError(f"Invalid aspect ratio: {value}")
    return width, height


def _parse_size(value: str) -> tuple[int, int]:
    width_str, height_str = value.lower().split("x", 1)
    width = int(width_str)
    height = int(height_str)
    if width <= 0 or height <= 0:
        raise ValueError(f"Invalid size: {value}")
    return width, height


def _even(value: int) -> int:
    return value if value % 2 == 0 else value - 1


def _probe_video_dimensions(video_path: str) -> tuple[int, int]:
    command = [
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=width,height",
        "-of",
        "json",
        video_path,
    ]
    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise ValueError(f"ffprobe failed: {result.stderr[-200:]}")
    data = json.loads(result.stdout)
    stream = (data.get("streams") or [{}])[0]
    width = int(stream["width"])
    height = int(stream["height"])
    return width, height


def _probe_video_duration(video_path: str) -> float:
    """Return video duration in seconds as a float."""
    command = [
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "format=duration",
        "-of",
        "default=noprint_wrappers=1:nokey=1",
        video_path,
    ]
    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise ValueError(f"ffprobe duration failed: {result.stderr[-200:]}")
    return float(result.stdout.strip())


def _trim_tail(
    *,
    video_bytes: bytes,
    trim_ms: int,
    post_id: str,
    correlation_id: str,
) -> tuple[bytes, Dict[str, Any]]:
    """Trim the last `trim_ms` milliseconds from a video using ffmpeg stream copy."""
    if trim_ms <= 0:
        return video_bytes, {}

    with tempfile.TemporaryDirectory(prefix="video_trim_") as temp_dir:
        input_path = os.path.join(temp_dir, "input.mp4")
        output_path = os.path.join(temp_dir, "output.mp4")
        with open(input_path, "wb") as file_obj:
            file_obj.write(video_bytes)

        original_duration = _probe_video_duration(input_path)
        trim_seconds = trim_ms / 1000.0

        if original_duration <= trim_seconds:
            logger.warning(
                "trim_tail_skipped_too_short",
                post_id=post_id,
                correlation_id=correlation_id,
                original_duration=original_duration,
                trim_ms=trim_ms,
            )
            return video_bytes, {"trim_tail_skipped": True}

        target_duration = original_duration - trim_seconds

        command = [
            "ffmpeg",
            "-y",
            "-i",
            input_path,
            "-t",
            f"{target_duration:.3f}",
            "-c",
            "copy",
            "-movflags",
            "+faststart",
            output_path,
        ]
        result = subprocess.run(command, capture_output=True, text=True, timeout=60)
        if result.returncode != 0:
            raise ValueError(f"ffmpeg trim failed: {result.stderr[-300:]}")

        final_duration = _probe_video_duration(output_path)

        with open(output_path, "rb") as file_obj:
            trimmed_bytes = file_obj.read()

    logger.info(
        "trim_tail_applied",
        post_id=post_id,
        correlation_id=correlation_id,
        original_duration_ms=round(original_duration * 1000),
        final_duration_ms=round(final_duration * 1000),
        trim_ms=trim_ms,
    )

    return trimmed_bytes, {
        "trim_tail_ms": trim_ms,
        "trim_original_duration_ms": round(original_duration * 1000),
        "trim_final_duration_ms": round(final_duration * 1000),
    }


def _maybe_postprocess_video_bytes(
    *,
    post_id: str,
    video_bytes: bytes,
    existing_metadata: Dict[str, Any],
    correlation_id: str,
) -> tuple[bytes, Dict[str, Any]]:
    target_aspect_ratio = str(existing_metadata.get("postprocess_crop_aspect_ratio") or "").strip()
    if not target_aspect_ratio:
        return video_bytes, {}

    requested_size = str(existing_metadata.get("requested_size") or "").strip()
    if not requested_size:
        raise ValueError(f"Post {post_id} is missing requested_size for crop postprocess")

    target_aspect_width, target_aspect_height = _parse_aspect_ratio(target_aspect_ratio)
    target_width, target_height = _parse_size(requested_size)

    with tempfile.TemporaryDirectory(prefix="video_postprocess_") as temp_dir:
        input_path = os.path.join(temp_dir, "input.mp4")
        output_path = os.path.join(temp_dir, "output.mp4")
        with open(input_path, "wb") as file_obj:
            file_obj.write(video_bytes)

        source_width, source_height = _probe_video_dimensions(input_path)
        source_ratio = source_width / source_height
        target_ratio = target_aspect_width / target_aspect_height

        if abs(source_ratio - target_ratio) < 0.001:
            crop_width = source_width
            crop_height = source_height
            crop_x = 0
            crop_y = 0
        elif source_ratio > target_ratio:
            crop_height = source_height
            crop_width = _even(int(source_height * target_ratio))
            crop_x = max((source_width - crop_width) // 2, 0)
            crop_y = 0
        else:
            crop_width = source_width
            crop_height = _even(int(source_width / target_ratio))
            crop_x = 0
            crop_y = max((source_height - crop_height) // 2, 0)

        filter_graph = (
            f"crop={crop_width}:{crop_height}:{crop_x}:{crop_y},"
            f"scale={target_width}:{target_height}"
        )
        command = [
            "ffmpeg",
            "-y",
            "-i",
            input_path,
            "-vf",
            filter_graph,
            "-map",
            "0:v:0",
            "-map",
            "0:a?",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "18",
            "-c:a",
            "copy",
            "-movflags",
            "+faststart",
            output_path,
        ]
        result = subprocess.run(command, capture_output=True, text=True, timeout=180)
        if result.returncode != 0:
            raise ValueError(f"ffmpeg postprocess failed: {result.stderr[-300:]}")

        with open(output_path, "rb") as file_obj:
            processed_bytes = file_obj.read()

    logger.info(
        "video_postprocess_crop_applied",
        post_id=post_id,
        correlation_id=correlation_id,
        target_aspect_ratio=target_aspect_ratio,
        source_size=f"{source_width}x{source_height}",
        output_size=f"{target_width}x{target_height}",
        filter_graph=filter_graph,
    )
    return processed_bytes, {
        "postprocess_crop_applied": True,
        "postprocess_crop_source_size": f"{source_width}x{source_height}",
        "postprocess_crop_output_size": f"{target_width}x{target_height}",
        "postprocess_crop_filter": filter_graph,
    }


def poll_pending_videos():
    """
    Poll all posts with submitted/processing video status.
    Per Constitution § VIII: Test end-to-end in real environment.
    """
    try:
        supabase = get_supabase().client
        
        # Fetch posts awaiting video completion
        response = supabase.table("posts").select("*").in_(
            "video_status", list(get_pollable_video_statuses())
        ).execute()
        
        posts = response.data
        logger.info("polling_videos", count=len(posts))
        
        for post in posts:
            process_video_operation(post)

        _reconcile_batches_ready_for_qa()
    
    except Exception as e:
        logger.exception("poll_cycle_failed", error=str(e))


def process_video_operation(post: Dict[str, Any]):
    """
    Process single video operation.
    Per Constitution § X: Hypothesis-driven debugging with structured evidence.
    """
    post_id = post["id"]
    correlation_id = f"poll_{post_id}"

    claimed_post = _claim_video_poll_lease(post, correlation_id)
    if claimed_post is None:
        return

    post = claimed_post
    operation_id = post.get("video_operation_id")
    provider = post.get("video_provider")

    if not operation_id or not provider:
        logger.warning(
            "missing_operation_data",
            post_id=post_id,
            has_operation_id=bool(operation_id),
            has_provider=bool(provider)
        )
        return
    
    try:
        if provider == "veo_3_1":
            if not _veo_available or get_veo_client is None:
                logger.warning(
                    "veo_poll_skipped",
                    post_id=post_id,
                    provider=provider,
                    reason="VEO client unavailable on this runtime"
                )
                return

            _handle_veo_video(post, operation_id, correlation_id)
        elif provider in {"sora_2", "sora_2_pro"}:
            _handle_sora_video(post, operation_id, correlation_id)
        elif provider == "vertex_ai":
            if not _vertex_ai_available or get_vertex_ai_client is None:
                logger.warning(
                    "vertex_ai_poll_skipped",
                    post_id=post_id,
                    provider=provider,
                    reason="Vertex AI client unavailable on this runtime"
                )
                return
            _handle_vertex_ai_video(post, operation_id, correlation_id)
        else:
            logger.warning(
                "unsupported_provider",
                post_id=post_id,
                provider=provider
            )
    
    except Exception as e:
        logger.exception(
            "video_processing_failed",
            post_id=post_id,
            correlation_id=correlation_id,
            operation_id=operation_id,
            provider=provider,
            poller_identity=_poller_identity(),
            error=str(e)
        )

        metadata = post.get("video_metadata") or {}
        if provider == "vertex_ai":
            retry_metadata = {
                **metadata,
                "error": str(e),
                "error_type": e.__class__.__name__,
                "provider": provider,
                "operation_id": operation_id,
                "last_polled_by": _poller_identity(),
                "last_polled_at": _utc_now_iso(),
            }
            if isinstance(e, httpx.HTTPStatusError):
                retry_metadata["provider_status_code"] = e.response.status_code
                retry_metadata["provider_response_body"] = e.response.text[:4000]

            try:
                supabase = get_supabase().client
                supabase.table("posts").update({
                    "video_status": "processing",
                    "video_metadata": retry_metadata,
                }).eq("id", post_id).execute()
                logger.warning(
                    "vertex_video_polling_deferred",
                    post_id=post_id,
                    correlation_id=correlation_id,
                    operation_id=operation_id,
                    error_type=e.__class__.__name__,
                )
                return
            except Exception as update_error:
                logger.exception(
                    "vertex_video_polling_deferral_failed",
                    post_id=post_id,
                    correlation_id=correlation_id,
                    operation_id=operation_id,
                    error=str(update_error),
                )
        if provider == "veo_3_1":
            if isinstance(e, httpx.HTTPStatusError) and e.response.status_code == 429:
                if _quota_controls_bypassed():
                    logger.warning(
                        "provider_429_freeze_suppressed_for_test",
                        post_id=post_id,
                        correlation_id=correlation_id,
                        provider=provider,
                        error=str(e),
                    )
                else:
                    maybe_freeze_after_provider_429(
                        provider="veo_3_1",
                        reason=str(e),
                    )
                _release_post_quota_reservation(
                    post,
                    reason=str(e),
                    final_status="failed",
                    error_code="provider_429",
                )
            else:
                chain_done = (metadata.get("video_pipeline_route") != VEO_EXTENDED_VIDEO_ROUTE) or (
                    not _needs_extension_hop(metadata)
                )
                if not chain_done:
                    _release_post_quota_reservation(
                        post,
                        reason=str(e),
                        final_status="failed",
                        error_code=e.__class__.__name__,
                    )
        
        # Mark as failed after exception
        try:
            supabase = get_supabase().client
            supabase.table("posts").update({
                "video_status": "failed",
                "video_metadata": {
                    **(post.get("video_metadata") or {}),
                    **_failure_metadata(
                        error=e,
                        provider=provider,
                        operation_id=operation_id,
                    ),
                },
            }).eq("id", post_id).execute()
            
            logger.error(
                "video_marked_failed",
                post_id=post_id,
                correlation_id=correlation_id
            )
        except Exception as update_error:
            logger.exception(
                "failed_to_mark_video_failed",
                post_id=post_id,
                error=str(update_error)
            )


def _retry_rai_filtered_video(post: Dict[str, Any], correlation_id: str, rai_reason: str) -> None:
    """Resubmit a video that was blocked by Google's RAI safety filter.

    Fetches the original prompt from video_prompt_audit and resubmits to Veo.
    Tracks retry count in video_metadata so the UI can show progress.
    """
    post_id = post["id"]
    metadata = dict(post.get("video_metadata") or {})
    rai_retries = metadata.get("rai_retry_count", 0)

    if rai_retries >= RAI_MAX_RETRIES:
        logger.warning(
            "rai_retry_exhausted",
            post_id=post_id,
            correlation_id=correlation_id,
            rai_retries=rai_retries,
            rai_reason=rai_reason,
        )
        raise ValueError(
            f"Safety filter blocked video after {rai_retries} retries. "
            f"Reason: {rai_reason}"
        )

    supabase = get_supabase().client

    # Fetch original prompt from audit table
    audit_rows = (
        supabase.table("video_prompt_audit")
        .select("prompt_text, negative_prompt, aspect_ratio, resolution, requested_seconds")
        .eq("post_id", post_id)
        .order("created_at", desc=True)
        .limit(1)
        .execute()
    ).data

    if not audit_rows:
        raise ValueError(
            f"Cannot retry RAI-filtered video for post {post_id}: "
            f"no prompt found in video_prompt_audit"
        )

    audit = audit_rows[0]
    retry_num = rai_retries + 1

    logger.info(
        "rai_retry_submitting",
        post_id=post_id,
        correlation_id=correlation_id,
        retry_number=retry_num,
        max_retries=RAI_MAX_RETRIES,
        rai_reason=rai_reason,
    )

    veo_client = get_veo_client()
    duration_seconds = (
        metadata.get("veo_base_seconds")
        if metadata.get("video_pipeline_route") == VEO_EXTENDED_VIDEO_ROUTE
        else audit["requested_seconds"]
    )
    if duration_seconds not in {4, 6, 8}:
        duration_seconds = 8
    if not _quota_controls_bypassed():
        ensure_immediate_submit_slot(provider="veo_3_1")
    else:
        logger.warning(
            "rai_retry_quota_controls_bypassed",
            post_id=post_id,
            correlation_id=correlation_id,
            retry_number=retry_num,
        )
    retry_reservation_key = build_reservation_key(
        provider="veo_3_1",
        post_id=post_id,
        correlation_id=f"{correlation_id}_rai_retry_{retry_num}",
        kind="retry_submit",
    )
    if not _quota_controls_bypassed():
        reserve_quota(
            provider="veo_3_1",
            post_id=post_id,
            batch_id=post.get("batch_id"),
            reservation_key=retry_reservation_key,
            requested_units=1,
            require_immediate_slot=False,
            reservation_kind="retry_submit",
        )
    quota_consume_error = None
    try:
        result = veo_client.submit_video_generation(
            prompt=audit["prompt_text"],
            negative_prompt=audit.get("negative_prompt"),
            correlation_id=f"{correlation_id}_rai_retry_{retry_num}",
            aspect_ratio=audit["aspect_ratio"],
            resolution=audit["resolution"],
            duration_seconds=duration_seconds,
            seed=audit.get("seed"),
        )
        if not _quota_controls_bypassed():
            quota_consume_error = _consume_quota_after_acceptance(
                reservation_key=retry_reservation_key,
                operation_id=result["operation_id"],
                units=1,
                correlation_id=correlation_id,
                post_id=post_id,
            )
    except Exception as exc:
        if not _quota_controls_bypassed() and not quota_consume_error:
            release_quota(
                reservation_key=retry_reservation_key,
                reason=str(exc),
                final_status="released",
                error_code=exc.__class__.__name__,
            )
        if isinstance(exc, httpx.HTTPStatusError) and exc.response.status_code == 429:
            if _quota_controls_bypassed():
                logger.warning(
                    "rai_retry_freeze_suppressed_for_test",
                    post_id=post_id,
                    correlation_id=correlation_id,
                    retry_number=retry_num,
                    error=str(exc),
                )
            else:
                maybe_freeze_after_provider_429(provider="veo_3_1", reason=str(exc))
        raise

    new_operation_id = result["operation_id"]
    operation_ids = list(metadata.get("operation_ids") or [])
    operation_ids.append(new_operation_id)

    metadata.update({
        "rai_retry_count": retry_num,
        "rai_last_reason": rai_reason,
        "rai_last_retry_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "operation_ids": operation_ids,
    })
    if quota_consume_error:
        metadata["quota_consume_error"] = quota_consume_error
    # Clear failure fields so the post re-enters the polling loop
    metadata.pop("error", None)
    metadata.pop("error_type", None)
    metadata.pop("failed_at", None)

    supabase.table("posts").update({
        "video_operation_id": new_operation_id,
        "video_status": "submitted",
        "video_metadata": metadata,
    }).eq("id", post_id).execute()

    logger.info(
        "rai_retry_submitted",
        post_id=post_id,
        correlation_id=correlation_id,
        retry_number=retry_num,
        new_operation_id=new_operation_id,
    )


def _handle_veo_video(post: Dict[str, Any], operation_id: str, correlation_id: str) -> None:
    post_id = post["id"]
    veo_client = get_veo_client()
    status_result = veo_client.check_operation_status(
        operation_id=operation_id,
        correlation_id=correlation_id
    )

    if status_result.get("status") == "failed":
        error = status_result.get("error") or {}
        error_message = error.get("message") or "Veo operation failed without an error message"
        error_code = error.get("code")

        # Auto-retry RAI-filtered videos
        if error_code == "RAI_FILTERED":
            _retry_rai_filtered_video(post, correlation_id, error_message)
            return

        if error_code is not None:
            raise ValueError(f"Veo operation failed ({error_code}): {error_message}")
        raise ValueError(f"Veo operation failed: {error_message}")

    if status_result["done"]:
        video_data = status_result.get("video_data")

        if not video_data or not video_data.get("video_uri"):
            logger.error(
                "video_data_missing_uri",
                post_id=post_id,
                correlation_id=correlation_id,
                operation_id=operation_id
            )
            raise ValueError("Video data missing download URI")

        # Check if this is an extended pipeline that needs more hops
        metadata = post.get("video_metadata") or {}
        if _needs_extension_hop(metadata):
            _submit_extension_hop(
                post,
                correlation_id=correlation_id,
                previous_video_data=video_data,
            )
            return

        video_uri = video_data["video_uri"]

        settings = get_settings()
        requires_local_postprocess = bool(metadata.get("postprocess_crop_aspect_ratio"))

        if settings.use_url_based_upload and not requires_local_postprocess:
            try:
                logger.info(
                    "attempting_url_based_upload",
                    post_id=post_id,
                    correlation_id=correlation_id,
                    video_uri_preview=video_uri[:100]
                )

                download_url = veo_client.get_video_download_url(
                    video_uri=video_uri,
                    correlation_id=correlation_id
                )

                _store_completed_video(
                    post_id=post_id,
                    provider="veo_3_1",
                    video_source=download_url,
                    correlation_id=correlation_id,
                    provider_metadata=video_data,
                    existing_metadata=post.get("video_metadata") or {}
                )

                return

            except Exception as url_upload_error:
                logger.warning(
                    "url_upload_failed_using_bytes_fallback",
                    post_id=post_id,
                    correlation_id=correlation_id,
                    error=str(url_upload_error)
                )

        video_bytes = veo_client.download_video(
            video_uri=video_uri,
            correlation_id=correlation_id
        )

        _store_completed_video(
            post_id=post_id,
            provider="veo_3_1",
            video_source=video_bytes,
            correlation_id=correlation_id,
            provider_metadata=video_data,
            existing_metadata=post.get("video_metadata") or {}
        )
    else:
        _mark_processing(post_id, correlation_id, operation_id)


def _handle_sora_video(post: Dict[str, Any], operation_id: str, correlation_id: str) -> None:
    post_id = post["id"]
    provider = post.get("video_provider", "sora_2")
    sora_client = get_sora_client()

    status_result = sora_client.check_video_status(
        video_id=operation_id,
        correlation_id=correlation_id
    )

    status = status_result.get("status", "queued")
    progress = status_result.get("progress")

    logger.debug(
        "sora_status_polled",
        post_id=post_id,
        correlation_id=correlation_id,
        status=status,
        progress=progress
    )

    if status == "completed":
        video_bytes = sora_client.download_video(
            video_id=operation_id,
            correlation_id=correlation_id,
        )

        _store_completed_video(
            post_id=post_id,
            provider=provider,
            video_source=video_bytes,
            correlation_id=correlation_id,
            provider_metadata=status_result,
            existing_metadata=post.get("video_metadata") or {}
        )
    elif status in {"failed", "cancelled"}:
        raise ValueError(f"Sora video failed with status {status}")
    else:
        new_status = "processing" if status in {"in_progress", "processing"} else "submitted"
        supabase = get_supabase().client
        supabase.table("posts").update({
            "video_status": new_status,
            "video_metadata": {
                **(post.get("video_metadata") or {}),
                "provider": provider,
                "progress": progress,
                "provider_status": status,
            }
        }).eq("id", post_id).execute()


def _handle_vertex_ai_video(post: Dict[str, Any], operation_id: str, correlation_id: str) -> None:
    post_id = post["id"]
    provider = post.get("video_provider", "vertex_ai")
    vertex_client = get_vertex_ai_client()

    status_result = vertex_client.check_operation_status(
        operation_id=operation_id,
        correlation_id=correlation_id,
    )

    done = status_result.get("done", False)
    video_uri = status_result.get("video_uri")

    logger.debug(
        "vertex_ai_status_polled",
        post_id=post_id,
        correlation_id=correlation_id,
        done=done,
        has_video_uri=bool(video_uri),
    )

    if done and video_uri:
        metadata = post.get("video_metadata") or {}
        if _needs_extension_hop(metadata):
            try:
                _submit_extension_hop(
                    post,
                    correlation_id=correlation_id,
                    previous_video_data=status_result,
                )
            except httpx.HTTPStatusError as error:
                if error.response.status_code == 429:
                    _defer_vertex_extension_rate_limit(
                        post_id=post_id,
                        metadata=metadata,
                        correlation_id=correlation_id,
                        error=error,
                    )
                    return
                raise
            return

        video_source = _decode_vertex_video_uri(video_uri)
        _store_completed_video(
            post_id=post_id,
            provider=provider,
            video_source=video_source,
            correlation_id=correlation_id,
            provider_metadata=status_result,
            existing_metadata=metadata,
        )
    elif done and not video_uri:
        raise ValueError("Vertex AI operation completed but returned no video URI")
    else:
        new_status = "processing"
        supabase = get_supabase().client
        supabase.table("posts").update({
            "video_status": new_status,
            "video_metadata": {
                **(post.get("video_metadata") or {}),
                "provider": provider,
                "provider_status": status_result.get("status"),
            }
        }).eq("id", post_id).execute()


def _decode_vertex_video_uri(video_uri: str) -> bytes:
    """Decode a Vertex AI data URI (data:video/mp4;base64,...) to bytes."""
    if video_uri.startswith("data:"):
        header, b64_data = video_uri.split(",", 1)
        import base64
        return base64.b64decode(b64_data)
    if video_uri.startswith("gs://"):
        _ensure_google_adc_env()
        bucket_and_object = video_uri[5:]
        bucket, _, object_name = bucket_and_object.partition("/")
        if not bucket or not object_name:
            raise ValueError(f"Invalid Vertex GCS URI: {video_uri}")
        credentials, _ = google.auth.default(scopes=["https://www.googleapis.com/auth/devstorage.read_only"])
        if credentials.expired or not credentials.token:
            credentials.refresh(Request())
        object_path = quote(object_name, safe="")
        url = f"https://storage.googleapis.com/storage/v1/b/{bucket}/o/{object_path}?alt=media"
        response = httpx.get(
            url,
            headers={"Authorization": f"Bearer {credentials.token}"},
            follow_redirects=True,
            timeout=120.0,
        )
        response.raise_for_status()
        return response.content
    return video_uri


def _stage_vertex_video_bytes_to_gcs(
    *,
    video_bytes: bytes,
    correlation_id: str,
    post_id: str,
    object_name: str,
) -> str:
    settings = get_settings()
    output_gcs_uri = (settings.vertex_ai_output_gcs_uri or "").strip()
    if not output_gcs_uri.startswith("gs://"):
        raise ValidationError(
            "VERTEX_AI_OUTPUT_GCS_URI must be set to a gs:// bucket prefix for Vertex extension staging.",
            details={"vertex_ai_output_gcs_uri": output_gcs_uri},
        )

    bucket_and_prefix = output_gcs_uri[5:]
    bucket, _, prefix = bucket_and_prefix.partition("/")
    if not bucket:
        raise ValidationError(
            "VERTEX_AI_OUTPUT_GCS_URI must include a bucket name.",
            details={"vertex_ai_output_gcs_uri": output_gcs_uri},
        )

    normalized_object_name = object_name.strip().lstrip("/")
    if prefix:
        normalized_object_name = f"{prefix.rstrip('/')}/{normalized_object_name}"

    _ensure_google_adc_env()
    credentials, _ = google.auth.default(
        scopes=["https://www.googleapis.com/auth/devstorage.read_write"]
    )
    if credentials.expired or not credentials.token:
        credentials.refresh(Request())

    url = (
        f"https://storage.googleapis.com/upload/storage/v1/b/{bucket}/o"
        f"?uploadType=media&name={quote(normalized_object_name, safe='')}"
    )
    response = httpx.post(
        url,
        content=video_bytes,
        headers={
            "Authorization": f"Bearer {credentials.token}",
            "Content-Type": "video/mp4",
        },
        timeout=120.0,
    )
    response.raise_for_status()
    return f"gs://{bucket}/{normalized_object_name}"


def _store_completed_video(
    *,
    post_id: str,
    provider: str,
    video_source: Union[bytes, str],
    correlation_id: str,
    provider_metadata: Dict[str, Any],
    existing_metadata: Dict[str, Any],
) -> None:
    storage_client = get_storage_client()
    processed_source = video_source
    postprocess_metadata: Dict[str, Any] = {}

    if isinstance(video_source, bytes):
        processed_source, postprocess_metadata = _maybe_postprocess_video_bytes(
            post_id=post_id,
            video_bytes=video_source,
            existing_metadata=existing_metadata,
            correlation_id=correlation_id,
        )

    if isinstance(processed_source, bytes) and TRIM_TAIL_MS > 0:
        try:
            processed_source, trim_metadata = _trim_tail(
                video_bytes=processed_source,
                trim_ms=TRIM_TAIL_MS,
                post_id=post_id,
                correlation_id=correlation_id,
            )
            postprocess_metadata.update(trim_metadata)
        except Exception:
            logger.exception(
                "trim_tail_failed_using_original",
                post_id=post_id,
                correlation_id=correlation_id,
            )

    upload_method = "url" if isinstance(processed_source, str) else "bytes"
    upload_start = time.monotonic()

    if upload_method == "url":
        upload_result = storage_client.upload_video_from_url(
            video_url=processed_source,
            file_name=f"post_{post_id}.mp4",
            correlation_id=correlation_id
        )
    else:
        upload_result = storage_client.upload_video(
            video_bytes=processed_source,
            file_name=f"post_{post_id}.mp4",
            correlation_id=correlation_id
        )

    upload_duration = time.monotonic() - upload_start

    if isinstance(processed_source, bytes):
        size_bytes = len(processed_source)
    else:
        size_bytes = upload_result.get("size")

    logger.info(
        "video_upload_performance",
        post_id=post_id,
        correlation_id=correlation_id,
        provider=provider,
        storage_provider=upload_result["storage_provider"],
        upload_method=upload_method,
        upload_duration_seconds=upload_duration,
        video_size_bytes=size_bytes
    )

    supabase = get_supabase().client
    merged_metadata = {
        **existing_metadata,
        "storage_provider": upload_result["storage_provider"],
        "storage_key": upload_result["storage_key"],
        "size_bytes": size_bytes,
        "provider": provider,
        "file_path": upload_result["file_path"],
        "thumbnail_url": upload_result.get("thumbnail_url"),
        "provider_metadata": provider_metadata,
        "upload_method": upload_method,
        "last_polled_by": _poller_identity(),
        "completed_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        **postprocess_metadata,
    }

    supabase.table("posts").update({
        "video_status": VIDEO_STATUS_CAPTION_PENDING,
        "video_url": upload_result["url"],
        "video_metadata": merged_metadata,
    }).eq("id", post_id).execute()

    logger.info(
        "video_completed",
        post_id=post_id,
        correlation_id=correlation_id,
        provider=provider,
        storage_provider=upload_result["storage_provider"],
        video_url=upload_result["url"],
        size_bytes=size_bytes,
        upload_method=upload_method,
        upload_duration_seconds=upload_duration
    )

    reservation_key = _quota_reservation_key(existing_metadata)
    if reservation_key:
        try:
            release_quota(
                reservation_key=reservation_key,
                reason="Video chain completed successfully.",
                final_status="completed",
            )
        except Exception:
            logger.exception(
                "quota_completion_finalize_failed",
                post_id=post_id,
                correlation_id=correlation_id,
                reservation_key=reservation_key,
            )

    segments = existing_metadata.get("veo_segments") or []
    operation_ids = list(existing_metadata.get("operation_ids") or [])
    word_count = sum(len(str(segment).split()) for segment in segments) if segments else None
    requested_base_duration = (
        existing_metadata.get("veo_base_seconds")
        if existing_metadata.get("video_pipeline_route") == VEO_EXTENDED_VIDEO_ROUTE
        else existing_metadata.get("provider_target_seconds") or existing_metadata.get("requested_seconds")
    )

    logger.info(
        "video_completion_summary",
        post_id=post_id,
        correlation_id=correlation_id,
        provider=provider,
        script_word_count=word_count,
        segment_count=len(segments) if segments else None,
        requested_base_duration_seconds=requested_base_duration,
        trimmed_duration_ms=merged_metadata.get("trim_final_duration_ms"),
        total_operation_count=len(operation_ids) if operation_ids else 1,
    )


def _mark_processing(post_id: str, correlation_id: str, operation_id: str) -> None:
    supabase = get_supabase().client
    post_response = supabase.table("posts").select("video_metadata").eq("id", post_id).single().execute()
    existing_metadata = (post_response.data or {}).get("video_metadata") or {}
    supabase.table("posts").update({
        "video_status": "processing",
        "video_metadata": {
            **existing_metadata,
            "last_polled_by": _poller_identity(),
            "last_polled_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "operation_id": operation_id,
        },
    }).eq("id", post_id).execute()

    logger.debug(
        "video_still_processing",
        post_id=post_id,
        correlation_id=correlation_id,
        operation_id=operation_id
    )


def _build_veo_extension_prompt(
    post: Dict[str, Any],
    segment_index: Optional[int] = None,
) -> Dict[str, str]:
    """Build a VEO extension prompt for the given post and segment index."""
    from app.features.posts.prompt_builder import (
        VEO_NEGATIVE_PROMPT,
        build_lean_veo_continuation_prompt,
        split_dialogue_sentences,
    )

    seed_data = post.get("seed_data") or {}
    metadata = post.get("video_metadata") or {}
    if isinstance(seed_data, str):
        import json as _json
        try:
            seed_data = _json.loads(seed_data)
        except _json.JSONDecodeError:
            seed_data = {}

    video_prompt = post.get("video_prompt_json") or {}
    if isinstance(video_prompt, str):
        try:
            video_prompt = _json.loads(video_prompt)
        except _json.JSONDecodeError:
            video_prompt = {}
    if not isinstance(video_prompt, dict):
        video_prompt = {}
    prompt_audio = video_prompt.get("audio") or {}
    if not isinstance(prompt_audio, dict):
        prompt_audio = {}

    script = str(
        prompt_audio.get("dialogue")
        or seed_data.get("script")
        or seed_data.get("dialog_script")
        or ""
    ).strip()
    metadata_segments = metadata.get("veo_segments") or []
    segments = [str(segment).strip() for segment in metadata_segments if str(segment).strip()]
    if not segments:
        segments = split_dialogue_sentences(script) if script else []
        if not segments and script:
            segments = [script]

    idx = segment_index if segment_index is not None else 0
    if idx < len(segments):
        segment_text = segments[idx]
    else:
        raise ValidationError(
            "Veo extension prompt requested a segment beyond the available dialogue segments.",
            details={
                "segment_index": idx,
                "segments_available": len(segments),
                "veo_extension_hops_target": metadata.get("veo_extension_hops_target", 0),
            },
        )

    hops_target = metadata.get("veo_extension_hops_target", 0)
    hops_completed = metadata.get("veo_extension_hops_completed", 0)
    is_final = (hops_completed + 1) >= hops_target if hops_target > 0 else True
    prompt_text = build_lean_veo_continuation_prompt(
        segment_text,
        include_final_ending=is_final,
    )

    return {
        "prompt_text": prompt_text,
        "segment_text": segment_text,
        "negative_prompt": str(video_prompt.get("veo_negative_prompt") or VEO_NEGATIVE_PROMPT).strip(),
    }


def _needs_extension_hop(metadata: Optional[Dict[str, Any]]) -> bool:
    """Check whether a completed VEO operation still needs more extension hops."""
    if not metadata:
        return False
    if metadata.get("video_pipeline_route") != VEO_EXTENDED_VIDEO_ROUTE:
        return False
    target = metadata.get("veo_extension_hops_target", 0)
    completed = metadata.get("veo_extension_hops_completed", 0)
    return completed < target


def _submit_extension_hop(
    post: Dict[str, Any],
    *,
    correlation_id: str,
    previous_video_data: Optional[Dict[str, Any]] = None,
) -> None:
    """Submit the next VEO extension hop for an in-progress chain.

    The REST extension path accepts a previous video URI and returns a
    single combined video (original + extension).
    """
    post_id = post["id"]
    metadata = dict(post.get("video_metadata") or {})
    retry_after = _parse_utc_timestamp(metadata.get("veo_extension_retry_after"))
    now = _utc_now()

    if retry_after and retry_after > now:
        logger.info(
            "extension_hop_retry_backoff_active",
            post_id=post_id,
            correlation_id=correlation_id,
            retry_after=metadata.get("veo_extension_retry_after"),
            seconds_remaining=max(int((retry_after - now).total_seconds()), 1),
        )
        return

    hops_completed = metadata.get("veo_extension_hops_completed", 0)
    current_segment_idx = metadata.get("veo_current_segment_index", 0)
    segments = metadata.get("veo_segments") or []
    next_segment_idx = current_segment_idx + 1

    if next_segment_idx < len(segments):
        segment_text = segments[next_segment_idx]
    else:
        raise ValidationError(
            "Veo extension chain ran out of distinct dialogue segments before the final hop.",
            details={
                "next_segment_index": next_segment_idx,
                "segments_available": len(segments),
                "veo_extension_hops_target": metadata.get("veo_extension_hops_target", 0),
                "veo_extension_hops_completed": hops_completed,
                "post_id": post_id,
            },
        )

    is_final_hop = (hops_completed + 1) >= metadata.get("veo_extension_hops_target", 0)
    logger.info(
        "extension_hop_route_profile",
        post_id=post_id,
        correlation_id=correlation_id,
        route=metadata.get("video_pipeline_route"),
        target_length_tier=metadata.get("target_length_tier"),
        base_seconds=metadata.get("veo_base_seconds"),
        extension_seconds=metadata.get("veo_extension_seconds"),
        hop_target=metadata.get("veo_extension_hops_target"),
        hop_completed=hops_completed,
        final_hop=is_final_hop,
        experiment_enabled=metadata.get("veo_efficient_long_route_enabled"),
    )
    prompt_payload = _build_veo_extension_prompt(post, segment_index=next_segment_idx)
    prompt = prompt_payload["prompt_text"]
    negative_prompt = prompt_payload.get("negative_prompt")
    segment_text = prompt_payload["segment_text"]

    provider = post.get("video_provider", "veo_3_1")
    settings = get_settings()
    reservation_key = _quota_reservation_key(metadata)

    video_uri = (previous_video_data or {}).get("video_uri")
    video_mime_type = (previous_video_data or {}).get("mime_type") or "video/mp4"
    if video_uri and video_uri.startswith("data:"):
        video_bytes = _decode_vertex_video_uri(video_uri)
        video_uri = _stage_vertex_video_bytes_to_gcs(
            video_bytes=video_bytes,
            correlation_id=correlation_id,
            post_id=post_id,
            object_name=f"vertex-input/{post_id}/{hops_completed + 1}.mp4",
        )
    output_gcs_uri = (
        metadata.get("vertex_output_gcs_uri")
        or settings.vertex_ai_output_gcs_uri
        or None
    )
    if not video_uri:
        raise ValueError(
            f"Cannot extend video for post {post_id}: previous video_data "
            f"missing video_uri"
        )

    if provider != "vertex_ai" and _quota_controls_bypassed():
        logger.warning(
            "extension_hop_quota_controls_bypassed",
            post_id=post_id,
            correlation_id=correlation_id,
            hop_number=hops_completed + 1,
            hop_target=metadata.get("veo_extension_hops_target"),
        )
    elif provider != "vertex_ai":
        ensure_immediate_submit_slot(provider="veo_3_1")

    try:
        if provider == "vertex_ai":
            vertex_client = get_vertex_ai_client()
            result = vertex_client.submit_video_extension(
                prompt=prompt,
                video_uri=video_uri,
                video_mime_type=video_mime_type,
                correlation_id=f"{correlation_id}_ext_{hops_completed + 1}",
                aspect_ratio=metadata.get("provider_aspect_ratio", metadata.get("requested_aspect_ratio", "9:16")),
                duration_seconds=7,
                output_gcs_uri=output_gcs_uri,
            )
        else:
            veo_client = get_veo_client()
            result = veo_client.submit_video_extension(
                prompt=prompt,
                video_uri=video_uri,
                correlation_id=f"{correlation_id}_ext_{hops_completed + 1}",
                aspect_ratio=metadata.get("provider_aspect_ratio", metadata.get("requested_aspect_ratio", "9:16")),
                resolution=metadata.get("requested_resolution", "720p"),
                duration_seconds=7,
                negative_prompt=negative_prompt,
                seed=metadata.get("veo_seed"),
            )
    except httpx.HTTPStatusError as error:
        if provider != "vertex_ai" and _is_retryable_veo_extension_input_not_ready(error):
            _defer_extension_hop_retry(
                post_id=post_id,
                metadata=metadata,
                correlation_id=correlation_id,
                error=error,
            )
            return
        raise

    new_operation_id = result["operation_id"]
    quota_consume_error = _consume_quota_after_acceptance(
        reservation_key=reservation_key,
        operation_id=new_operation_id,
        units=1,
        correlation_id=correlation_id,
        post_id=post_id,
    )
    operation_ids = list(metadata.get("operation_ids") or [])
    operation_ids.append(new_operation_id)

    record_prompt_audit(
        post_id=post_id,
        batch_id=post.get("batch_id"),
        operation_id=new_operation_id,
        provider=provider,
        prompt_text=prompt,
        negative_prompt=negative_prompt,
        prompt_path="veo_extension_hop",
        aspect_ratio=metadata.get("provider_aspect_ratio", metadata.get("requested_aspect_ratio", "9:16")),
        resolution=metadata.get("requested_resolution", "720p"),
        requested_seconds=7,
        correlation_id=f"{correlation_id}_ext_{hops_completed + 1}",
    )

    extension_seconds = metadata.get("veo_extension_seconds", 7)
    generated_seconds = metadata.get("generated_seconds", 0) + extension_seconds
    lease_refreshed_at = _utc_now()
    poller_identity = _poller_identity()

    metadata.update({
        "veo_extension_hops_completed": hops_completed + 1,
        "veo_current_segment_index": next_segment_idx,
        "operation_ids": operation_ids,
        "chain_status": "extending",
        "generated_seconds": generated_seconds,
        "vertex_output_gcs_uri": output_gcs_uri,
        VIDEO_POLL_LEASE_OWNER_KEY: poller_identity,
        VIDEO_POLL_LEASE_ACQUIRED_KEY: _utc_now_iso(lease_refreshed_at),
        VIDEO_POLL_LEASE_EXPIRES_KEY: _utc_now_iso(lease_refreshed_at + timedelta(seconds=VIDEO_POLL_LEASE_SECONDS)),
        "last_polled_by": poller_identity,
        "last_polled_at": _utc_now_iso(lease_refreshed_at),
    })
    if quota_consume_error:
        metadata["quota_consume_error"] = quota_consume_error
    metadata.pop("veo_extension_retry_after", None)
    metadata.pop("veo_extension_last_retryable_error", None)
    metadata.pop("provider_status_code", None)
    metadata.pop("provider_response_body", None)
    metadata.pop("error", None)
    metadata.pop("error_type", None)

    supabase = get_supabase().client
    supabase.table("posts").update({
        "video_operation_id": new_operation_id,
        "video_status": "extended_submitted",
        "video_metadata": metadata,
    }).eq("id", post_id).execute()

    logger.info(
        "extension_hop_submitted",
        post_id=post_id,
        correlation_id=correlation_id,
        hop_number=hops_completed + 1,
        hops_target=metadata.get("veo_extension_hops_target"),
        operation_id=new_operation_id,
        segment_index=next_segment_idx,
        is_final_hop=is_final_hop,
    )


def _defer_vertex_extension_rate_limit(
    *,
    post_id: str,
    metadata: Dict[str, Any],
    correlation_id: str,
    error: httpx.HTTPStatusError,
) -> None:
    retry_count = int(metadata.get("veo_extension_rate_limit_retry_count") or 0) + 1
    delay_seconds = _veo_extension_retry_delay_seconds(retry_count)
    retry_after = _utc_now() + timedelta(seconds=delay_seconds)

    metadata.update(
        {
            "chain_status": "waiting_for_extension_input_processing",
            "veo_extension_rate_limit_retry_count": retry_count,
            "veo_extension_retry_after": _utc_now_iso(retry_after),
            "veo_extension_last_retryable_error": error.response.text[:4000],
            "provider_status_code": error.response.status_code,
            "provider_response_body": error.response.text[:4000],
            "last_polled_by": _poller_identity(),
            "last_polled_at": _utc_now_iso(),
        }
    )

    supabase = get_supabase().client
    supabase.table("posts").update(
        {
            "video_status": get_processing_video_status(VEO_EXTENDED_VIDEO_ROUTE),
            "video_metadata": metadata,
        }
    ).eq("id", post_id).execute()

    logger.warning(
        "vertex_extension_hop_deferred_rate_limited",
        post_id=post_id,
        correlation_id=correlation_id,
        retry_count=retry_count,
        retry_after=metadata["veo_extension_retry_after"],
        provider_status_code=error.response.status_code,
    )


def _check_and_transition_batch_to_qa(post_id: str, correlation_id: str) -> None:
    """
    Check if all videos in batch are complete and transition to S6_QA.
    Per Canon § 3.2: S5_PROMPTS_BUILT → S6_QA transition.
    Per Constitution § VII: State Machine Discipline with explicit guards.
    """
    try:
        supabase = get_supabase().client
        
        # Get batch_id from post
        post_response = supabase.table("posts").select("batch_id").eq("id", post_id).execute()
        if not post_response.data:
            logger.warning("post_not_found_for_qa_check", post_id=post_id)
            return
        
        batch_id = post_response.data[0]["batch_id"]

        _check_and_transition_batch_to_qa_by_batch_id(batch_id, correlation_id)
    
    except Exception as e:
        logger.exception(
            "batch_qa_transition_check_failed",
            post_id=post_id,
            correlation_id=correlation_id,
            error=str(e)
        )


def _check_and_transition_batch_to_qa_by_batch_id(batch_id: str, correlation_id: str) -> None:
    """Reconcile a batch through prompts/video milestones after a post update."""
    reconcile_batch_video_pipeline_state(
        batch_id=batch_id,
        correlation_id=correlation_id,
    )


def _reconcile_batches_ready_for_qa() -> None:
    """
    Re-check video pipeline batches every poll cycle so batches that missed the
    original S4->S5 or S5->S6 edge can still advance.
    """
    supabase = get_supabase().client
    response = (
        supabase.table("batches")
        .select("id")
        .in_("state", ["S4_SCRIPTED", "S5_PROMPTS_BUILT"])
        .execute()
    )
    batches = response.data or []

    logger.debug("reconciling_batches_ready_for_qa", count=len(batches))

    for batch in batches:
        batch_id = batch.get("id")
        if not batch_id:
            continue
        _check_and_transition_batch_to_qa_by_batch_id(
            batch_id,
            correlation_id=f"reconcile_{batch_id}"
        )


if __name__ == "__main__":
    settings = get_settings()
    if not settings.google_ai_keys_aligned():
        logger.warning(
            "google_ai_key_alignment_mismatch",
            gemini_api_key_present=bool(settings.gemini_api_key),
            google_ai_api_key_present=bool(settings.google_ai_api_key),
            message="GEMINI_API_KEY and GOOGLE_AI_API_KEY differ; continuing with the active Google AI key fingerprint",
        )

    logger.info(
        "video_poller_started",
        poll_interval_seconds=POLL_INTERVAL_SECONDS,
        poller_identity=_poller_identity(),
    )

    while True:
        try:
            poll_pending_videos()
        except KeyboardInterrupt:
            logger.info("video_poller_stopped_by_user")
            break
        except Exception as e:
            logger.exception("video_poller_unexpected_error", error=str(e))

        time.sleep(POLL_INTERVAL_SECONDS)
